# -*- coding: utf-8 -*-
"""Python Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trXHk_MngHCdBG64Td2-oGcQTVTNtAiW

# **Python Coding Assignment**

**Name -** Anil Kushwaha

**Mo.no-** 9829159839

**Email -** kumaranil48309@gmail.com
"""

from google.colab import files

print("Please upload PDF files :- ")  # SJS Transcript Call.pdf
uploaded = files.upload()  # Opens a file selection dialog

import fitz  # PyMuPDF for PDF text extraction
import re
from collections import defaultdict
from transformers import pipeline


def extract_text_from_pdf(pdf_path):
    """Extracts text from a PDF file."""
    text = ""
    with fitz.open(pdf_path) as doc:
        for page in doc:
            text += page.get_text("text") + "\n"
    return text

def extract_financial_data(text):
    """Extracts key financial metrics using regex patterns."""
    financial_info = defaultdict(list)

    patterns = {
        "revenue": r"(?:revenue|sales)[:\s]+Rs\.?[\s]*([0-9,]+\.?[0-9]*)\s*million",
        "ebitda": r"EBITDA[:\s]+Rs\.?[\s]*([0-9,]+\.?[0-9]*)\s*million",
        "pat": r"PAT[:\s]+Rs\.?[\s]*([0-9,]+\.?[0-9]*)\s*million",
        "growth": r"(?:growth|increase)[:\s]+([0-9]+\.?[0-9]*)%"
    }

    for key, pattern in patterns.items():
        matches = re.findall(pattern, text, re.IGNORECASE)
        if matches:
            financial_info[key] = [match.replace(",", "") for match in matches]

    return financial_info

def summarize_text(text):
    """Summarizes extracted text using an NLP model."""
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
    summary = summarizer(text[:1024], max_length=150, min_length=50, do_sample=False)  # Limit input size
    return summary[0]['summary_text']

def main():
    pdf_path = "/content/SJS Transcript Call.pdf"  # Uploaded PDF file
    text = extract_text_from_pdf(pdf_path)

    financial_data = extract_financial_data(text)
    summary = summarize_text(text)

    print("\nExtracted Financial Data:")
    for key, values in financial_data.items():
        print(f"{key.capitalize()}: {', '.join(values)}")

    print("\nSummarized Report:")
    print(summary)

if __name__ == "__main__":
    main()